// Network3.c
#include "Network3.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>

#include "edge_call.h"
#include "syscall.h"
#include "crypto.h"   // AES_BLOCKLEN, extern iv[], extern key[], AES_* APIs

#ifndef OCALL_PRINT_TIME
#define OCALL_PRINT_TIME 3
#endif

#define OCALL_PRINT_BUFFER 6
#define OCALL_PRINT_OUTPUT 10

/* Use the key declared in crypto.h (avoid multiple definitions) */
extern uint8_t key[AES_BLOCKLEN];
extern uint8_t iv[AES_BLOCKLEN];

/* OCall wrappers */
static unsigned long ocall_print_output(char *str) {
    unsigned long ret;
    ocall(OCALL_PRINT_OUTPUT, str, strlen(str) + 1, &ret, sizeof(ret));
    return ret;
}
static unsigned long ocall_print_time(char *str) {
    unsigned long ret;
    ocall(OCALL_PRINT_TIME, str, strlen(str) + 1, &ret, sizeof(ret));
    return ret;
}
static unsigned long ocall_print_buffer(char *str) {
    unsigned long ret;
    ocall(OCALL_PRINT_BUFFER, str, strlen(str) + 1, &ret, sizeof(ret));
    return ret;
}

/* Our own const-safe strlen to match SDK's non-const strlen(char*) */
static size_t cstrlen(const char *s) {
    const char *p = s;
    while (*p) ++p;
    return (size_t)(p - s);
}

static void concatStrings(char *dest, const char *src) {
    size_t dlen = cstrlen(dest);
    size_t slen = cstrlen(src);
    if (dlen + slen + 1 >= 2048) return;
    memcpy(dest + dlen, src, slen + 1);
}

/* List of 1000 class names (truncated for brevity) */
static const char* g_class_names[] = {
    "tench",
    "goldfish",
    "great",
    "tiger",
    "hammerhead",
    "electric",
    "stingray",
    "cock",
    "hen",
    "ostrich",
    "brambling",
    "goldfinch",
    "house",
    "junco",
    "indigo",
    "robin",
    "bulbul",
    "jay",
    "magpie",
    "chickadee",
    "water",
    "kite",
    "bald",
    "vulture",
    "great",
    "European",
    "common",
    "eft",
    "spotted",
    "axolotl",
    "bullfrog",
    "tree",
    "tailed",
    "loggerhead",
    "leatherback",
    "mud",
    "terrapin",
    "box",
    "banded",
    "common",
    "American",
    "whiptail",
    "agama",
    "frilled",
    "alligator",
    "Gila",
    "green",
    "African",
    "Komodo",
    "African",
    "American",
    "triceratops",
    "thunder",
    "ringneck",
    "hognose",
    "green",
    "king",
    "garter",
    "water",
    "vine",
    "night",
    "boa",
    "rock",
    "Indian",
    "green",
    "sea",
    "horned",
    "diamondback",
    "sidewinder",
    "trilobite",
    "harvestman",
    "scorpion",
    "black",
    "barn",
    "garden",
    "black",
    "tarantula",
    "wolf",
    "tick",
    "centipede",
    "black",
    "ptarmigan",
    "ruffed",
    "prairie",
    "peacock",
    "quail",
    "partridge",
    "African",
    "macaw",
    "sulphur",
    "lorikeet",
    "coucal",
    "bee",
    "hornbill",
    "hummingbird",
    "jacamar",
    "toucan",
    "drake",
    "red",
    "goose",
    "black",
    "tusker",
    "echidna",
    "platypus",
    "wallaby",
    "koala",
    "wombat",
    "jellyfish",
    "sea_anemone",
    "brain",
    "flatworm",
    "nematode",
    "conch",
    "snail",
    "slug",
    "sea",
    "chiton",
    "chambered",
    "Dungeness",
    "rock",
    "fiddler",
    "king",
    "American",
    "spiny",
    "crayfish",
    "hermit",
    "isopod",
    "white",
    "black",
    "spoonbill",
    "flamingo",
    "little",
    "American",
    "bittern",
    "crane",
    "limpkin",
    "European",
    "American",
    "bustard",
    "ruddy",
    "redbacked",
    "redshank",
    "dowitcher",
    "oystercatcher",
    "pelican",
    "king",
    "albatross",
    "grey",
    "killer",
    "dugong",
    "sea",
    "Chihuahua",
    "Japanese",
    "Maltese",
    "Pekinese",
    "Shih",
    "Blenheim",
    "papillon",
    "toy",
    "Rhodesian",
    "Afghan",
    "basset",
    "beagle",
    "bloodhound",
    "bluetick",
    "black",
    "Walker",
    "English",
    "redbone",
    "borzoi",
    "Irish",
    "Italian",
    "whippet",
    "Ibizan",
    "Norwegian",
    "otterhound",
    "Saluki",
    "Scottish",
    "Weimaraner",
    "Staffordshire",
    "American",
    "Bedlington",
    "Border",
    "Kerry",
    "Irish",
    "Norfolk",
    "Norwich",
    "Yorkshire",
    "wire",
    "Lakeland",
    "Sealyham",
    "Airedale",
    "cairn",
    "Australian",
    "Dandie",
    "Boston",
    "miniature",
    "giant",
    "standard",
    "Scotch",
    "Tibetan",
    "silky",
    "soft",
    "West",
    "Lhasa",
    "flat",
    "curly",
    "golden",
    "Labrador",
    "Chesapeake",
    "German",
    "vizsla",
    "English",
    "Irish",
    "Gordon",
    "Brittany",
    "clumber",
    "English",
    "Welsh",
    "cocker",
    "Sussex",
    "Irish",
    "kuvasz",
    "schipperke",
    "groenendael",
    "malinois",
    "briard",
    "kelpie",
    "komondor",
    "Old",
    "Shetland",
    "collie",
    "Border",
    "Bouvier",
    "Rottweiler",
    "German",
    "Doberman",
    "miniature",
    "Greater",
    "Bernese",
    "Appenzeller",
    "EntleBucher",
    "boxer",
    "bull",
    "Tibetan",
    "French",
    "Great",
    "Saint",
    "Eskimo",
    "malamute",
    "Siberian",
    "dalmatian",
    "affenpinscher",
    "basenji",
    "pug",
    "Leonberg",
    "Newfoundland",
    "Great",
    "Samoyed",
    "Pomeranian",
    "chow",
    "keeshond",
    "Brabancon",
    "Pembroke",
    "Cardigan",
    "toy",
    "miniature",
    "standard",
    "Mexican",
    "timber",
    "white",
    "red",
    "coyote",
    "dingo",
    "dhole",
    "African",
    "hyena",
    "red",
    "kit",
    "Arctic",
    "grey",
    "tabby",
    "tiger",
    "Persian",
    "Siamese",
    "Egyptian",
    "cougar",
    "lynx",
    "leopard",
    "snow",
    "jaguar",
    "lion",
    "tiger",
    "cheetah",
    "brown",
    "American",
    "ice",
    "sloth",
    "mongoose",
    "meerkat",
    "tiger",
    "ladybug",
    "ground",
    "long",
    "leaf",
    "dung",
    "rhinoceros",
    "weevil",
    "fly",
    "bee",
    "ant",
    "grasshopper",
    "cricket",
    "walking",
    "cockroach",
    "mantis",
    "cicada",
    "leafhopper",
    "lacewing",
    "dragonfly",
    "damselfly",
    "admiral",
    "ringlet",
    "monarch",
    "cabbage",
    "sulphur",
    "lycaenid",
    "starfish",
    "sea",
    "seacucumber",
    "wood",
    "hare",
    "Angora",
    "hamster",
    "porcupine",
    "fox",
    "marmot",
    "beaver",
    "guinea",
    "sorrel",
    "zebra",
    "hog",
    "wild",
    "warthog",
    "hippopotamus",
    "ox",
    "water",
    "bison",
    "ram",
    "bighorn",
    "ibex",
    "hartebeest",
    "impala",
    "gazelle",
    "Arabian",
    "llama",
    "weasel",
    "mink",
    "polecat",
    "black",
    "otter",
    "skunk",
    "badger",
    "armadillo",
    "three",
    "orangutan",
    "gorilla",
    "chimpanzee",
    "gibbon",
    "siamang",
    "guenon",
    "patas",
    "baboon",
    "macaque",
    "langur",
    "colobus",
    "proboscis",
    "marmoset",
    "capuchin",
    "howler",
    "titi",
    "spider",
    "squirrel",
    "Madagascar",
    "indri",
    "Indian",
    "Africanelephant",
    "lesser",
    "giant",
    "barracouta",
    "eel",
    "coho",
    "rock",
    "anemone",
    "sturgeon",
    "gar",
    "lionfish",
    "puffer",
    "abacus",
    "abaya",
    "academic",
    "accordion",
    "acoustic",
    "aircraft",
    "airliner",
    "airship",
    "altar",
    "ambulance",
    "amphibian",
    "analog",
    "apiary",
    "apron",
    "ashcan",
    "assault",
    "backpack",
    "bakery",
    "balance",
    "balloon",
    "ballpoint",
    "Band",
    "banjo",
    "bannister",
    "barbell",
    "barber",
    "barbershop",
    "barn",
    "barometer",
    "barrel",
    "barrow",
    "baseball",
    "basketball",
    "bassinet",
    "bassoon",
    "bathing",
    "bath",
    "bathtub",
    "beach_wagon",
    "beacon",
    "beaker",
    "bearskin",
    "beer",
    "beerglass",
    "bell",
    "bib",
    "bicycle",
    "bikini",
    "binder",
    "binoculars",
    "birdhouse",
    "boathouse",
    "bobsled",
    "bolo",
    "bonnet",
    "bookcase",
    "bookshop",
    "bottlecap",
    "bow",
    "bow",
    "brass",
    "brassiere",
    "breakwater",
    "breastplate",
    "broom",
    "bucket",
    "buckle",
    "bulletproof",
    "bullet",
    "butcher",
    "cab",
    "caldron",
    "candle",
    "cannon",
    "canoe",
    "can",
    "cardigan",
    "car",
    "carousel",
    "carpenter",
    "carton",
    "carwheel",
    "cash",
    "cassette",
    "cassetteplayer",
    "castle",
    "catamaran",
    "CD",
    "cello",
    "cellular",
    "chain",
    "chainlink",
    "chain",
    "chainsaw",
    "chest",
    "chiffonier",
    "chime",
    "china",
    "Christmas",
    "church",
    "cinema",
    "cleaver",
    "cliff",
    "cloak",
    "clog",
    "cocktail",
    "coffee",
    "coffeepot",
    "coil",
    "combination",
    "computer",
    "confectionery",
    "container",
    "convertible",
    "corkscrew",
    "cornet",
    "cowboy",
    "cowboyhat",
    "cradle",
    "crane",
    "crash",
    "crate",
    "crib",
    "Crock",
    "croquet",
    "crutch",
    "cuirass",
    "dam",
    "desk",
    "desktop",
    "dial",
    "diaper",
    "digital",
    "digitalwatch",
    "dining",
    "dishrag",
    "dishwasher",
    "disk",
    "dock",
    "dogsled",
    "dome",
    "doormat",
    "drilling",
    "drum",
    "drumstick",
    "dumbbell",
    "Dutch",
    "electricfan",
    "electricguitar",
    "electric",
    "entertainment",
    "envelope",
    "espresso",
    "face",
    "feather",
    "file",
    "fireboat",
    "fire",
    "firescreen",
    "flagpole",
    "flute",
    "folding",
    "football",
    "forklift",
    "fountain",
    "fountain",
    "four",
    "freight",
    "French",
    "frying",
    "fur",
    "garbage",
    "gasmask",
    "gas",
    "goblet",
    "go",
    "golf",
    "golfcart",
    "gondola",
    "gong",
    "gown",
    "grand",
    "greenhouse",
    "grille",
    "grocery",
    "guillotine",
    "hair",
    "hairspray",
    "halftrack",
    "hammer",
    "hamper",
    "hand",
    "handheld",
    "handkerchief",
    "hard",
    "harmonica",
    "harp",
    "harvester",
    "hatchet",
    "holster",
    "home",
    "honeycomb",
    "hook",
    "hoopskirt",
    "horizontal",
    "horse",
    "hourglass",
    "iPod",
    "iron",
    "jack",
    "jean",
    "jeep",
    "jersey",
    "jigsaw",
    "jinrikisha",
    "joystick",
    "kimono",
    "knee",
    "knot",
    "lab",
    "ladle",
    "lampshade",
    "laptop",
    "lawn",
    "lens",
    "letter",
    "library",
    "lifeboat",
    "lighter",
    "limousine",
    "liner",
    "lipstick",
    "Loafer",
    "lotion",
    "loudspeaker",
    "loupe",
    "lumbermill",
    "magnetic",
    "mailbag",
    "mailbox",
    "maillot",
    "maillot",
    "manhole",
    "maraca",
    "marimba",
    "mask",
    "matchstick",
    "maypole",
    "maze",
    "measuring",
    "medicine",
    "megalith",
    "microphone",
    "microwave",
    "military",
    "milk",
    "minibus",
    "miniskirt",
    "minivan",
    "missile",
    "mitten",
    "mixing",
    "mobile",
    "Model",
    "modem",
    "monastery",
    "monitor",
    "moped",
    "mortar",
    "mortarboard",
    "mosque",
    "mosquito",
    "motor",
    "mountain",
    "mountain",
    "mouse",
    "mousetrap",
    "moving",
    "muzzle",
    "nail",
    "neck",
    "necklace",
    "nipple",
    "notebook",
    "obelisk",
    "oboe",
    "ocarina",
    "odometer",
    "oil",
    "organ",
    "oscilloscope",
    "overskirt",
    "oxcart",
    "oxygen",
    "packet",
    "paddle",
    "paddlewheel",
    "padlock",
    "paintbrush",
    "pajama",
    "palace",
    "panpipe",
    "paper",
    "parachute",
    "parallel",
    "park",
    "parking",
    "passenger",
    "patio",
    "pay",
    "pedestal",
    "pencil",
    "pencil",
    "perfume",
    "Petri",
    "photocopier",
    "pick",
    "pickelhaube",
    "picket",
    "pickup",
    "pier",
    "piggy",
    "pill",
    "pillow",
    "ping",
    "pinwheel",
    "pirate",
    "pitcher",
    "plane",
    "planetarium",
    "plastic",
    "plate",
    "plow",
    "plunger",
    "Polaroid",
    "pole",
    "police",
    "poncho",
    "pool",
    "pop",
    "pot",
    "potter",
    "power",
    "prayer",
    "printer",
    "prison",
    "projectile",
    "projector",
    "puck",
    "punching",
    "purse",
    "quill",
    "quilt",
    "racer",
    "racket",
    "radiator",
    "radio",
    "radiotelescope",
    "rain",
    "recreational",
    "reel",
    "reflex",
    "refrigerator",
    "remote",
    "restaurant",
    "revolver",
    "rifle",
    "rocking",
    "rotisserie",
    "rubber",
    "rugby",
    "rule",
    "running",
    "safe",
    "safety",
    "saltshaker",
    "sandal",
    "sarong",
    "sax",
    "scabbard",
    "scale",
    "school",
    "schooner",
    "scoreboard",
    "screen",
    "screw",
    "screwdriver",
    "seat",
    "sewing",
    "shield",
    "shoe",
    "shoji",
    "shopping",
    "shoppingcart",
    "shovel",
    "showercap",
    "shower",
    "ski",
    "skimask",
    "sleeping",
    "slide",
    "sliding",
    "slot",
    "snorkel",
    "snowmobile",
    "snowplow",
    "soap",
    "soccer",
    "sock",
    "solar",
    "sombrero",
    "soup",
    "spacebar",
    "spaceheater",
    "space",
    "spatula",
    "speedboat",
    "spider",
    "spindle",
    "sports",
    "spotlight",
    "stage",
    "steam",
    "steel",
    "steeldrum",
    "stethoscope",
    "stole",
    "stone",
    "stopwatch",
    "stove",
    "strainer",
    "streetcar",
    "stretcher",
    "studio",
    "stupa",
    "submarine",
    "suit",
    "sundial",
    "sunglass",
    "sunglasses",
    "sunscreen",
    "suspension",
    "swab",
    "sweatshirt",
    "swimming",
    "swing",
    "switch",
    "syringe",
    "table",
    "tank",
    "tape",
    "teapot",
    "teddy",
    "television",
    "tennis",
    "thatch",
    "theater",
    "thimble",
    "thresher",
    "throne",
    "tile",
    "toaster",
    "tobacco",
    "toilet",
    "torch",
    "totem",
    "tow",
    "toyshop",
    "tractor",
    "trailer",
    "tray",
    "trench",
    "tricycle",
    "trimaran",
    "tripod",
    "triumphal",
    "trolleybus",
    "trombone",
    "tub",
    "turnstile",
    "typewriter",
    "umbrella",
    "unicycle",
    "upright",
    "vacuum",
    "vase",
    "vault",
    "velvet",
    "vending",
    "vestment",
    "viaduct",
    "violin",
    "volleyball",
    "waffle",
    "wall",
    "wallet",
    "wardrobe",
    "warplane",
    "washbasin",
    "washer",
    "water",
    "waterjug",
    "water",
    "whiskey",
    "whistle",
    "wig",
    "window",
    "windowshade",
    "Windsortie",
    "wine",
    "wing",
    "wok",
    "wooden",
    "wool",
    "worm",
    "wreck",
    "yawl",
    "yurt",
    "web",
    "comic",
    "crossword",
    "street",
    "traffic",
    "book",
    "menu",
    "plate",
    "guacamole",
    "consomme",
    "hot",
    "trifle",
    "icecream",
    "ice",
    "French",
    "bagel",
    "pretzel",
    "cheeseburger",
    "hotdog",
    "mashed",
    "head",
    "broccoli",
    "cauliflower",
    "zucchini",
    "spaghetti",
    "acorn",
    "butternut",
    "cucumber",
    "artichoke",
    "bell",
    "cardoon",
    "mushroom",
    "Granny",
    "strawberry",
    "orange",
    "lemon",
    "fig",
    "pineapple",
    "banana",
    "jackfruit",
    "custard",
    "pomegranate",
    "hay",
    "carbonara",
    "chocolate",
    "dough",
    "meat",
    "pizza",
    "potpie",
    "burrito",
    "red",
    "espresso",
    "cup",
    "eggnog",
    "alp",
    "bubble",
    "cliff",
    "coral",
    "geyser",
    "lakeside",
    "promontory",
    "sandbar",
    "seashore",
    "valley",
    "volcano",
    "ballplayer",
    "groom",
    "scuba",
    "rapeseed",
    "daisy",
    "yellow",
    "corn",
    "acorn",
    "hip",
    "buckeye",
    "coral",
    "agaric",
    "gyromitra",
    "stinkhorn",
    "earthstar",
    "hen",
    "bolete",
    "ear",
    "toilet"
};

Network3* Network3_create(void) {
    Network3 *net = (Network3*)malloc(sizeof(Network3));
    if (!net) return NULL;

    ocall_print_time("Network Init 3 Start\n");
    ocall_print_buffer("Initializing Network 3...\n");

    /* Fully-connected layer: fileNum=7, input=320, output=1000 */
    net->fc = FcLayer_create(7, 320, 1000);
    if (!net->fc) { free(net); return NULL; }

    net->class_names = g_class_names;
    net->class_count = sizeof(g_class_names) / sizeof(g_class_names[0]);

    ocall_print_buffer("Initializing Network 3 Done...\n");
    ocall_print_time("Network Init 3 End");
    return net;
}

void Network3_destroy(Network3* net) {
    if (!net) return;
    FcLayer_destroy(net->fc);
    free(net);
}

float* Network3_forward(Network3* net, float* input) {
    ocall_print_time("Inference 3 Start");
    ocall_print_buffer("Getting output...\n");

    /* Run FC layer */
    FcLayer_forward(net->fc, input);
    float *pfOutput = FcLayer_get_output(net->fc);
    int nOut = FcLayer_get_output_size(net->fc);

    /* Collect activated outputs > 0.5 */
    int ids[1000];
    float vals[1000];
    size_t count = 0;
    for (int i = 0; i < nOut; ++i) {
        if (pfOutput[i] > 0.5f && count < 1000) {
            ids[count] = i;
            vals[count] = pfOutput[i];
            count++;
        }
    }

    ocall_print_time("Inference 3 End");
    ocall_print_time("Communication 3 Start");

    /* Prepare AES-CBC context */
    struct AES_ctx ctx;
    AES_init_ctx_iv(&ctx, key, iv);

    /* Build output string (plaintext) */
    char outbuf[2048] = {0};
    for (size_t i = 0; i < count; ++i) {
        char tmp[64];
        /* vals, ids, and class name */
        snprintf(tmp, sizeof(tmp), "%f: %d: %s\n", vals[i], ids[i], net->class_names[ids[i]]);
        concatStrings(outbuf, tmp);
    }

    /* Pad and encrypt */
    size_t len = cstrlen(outbuf);
    size_t padded = len;
    uint8_t *buffer = (uint8_t*)malloc(padded + AES_BLOCKLEN);
    if (!buffer) {
        ocall_print_buffer("Allocation failed in Network3_forward\n");
        return pfOutput;
    }
    memcpy(buffer, outbuf, len);
    pad_buffer(buffer, &padded);
    AES_CBC_encrypt_buffer(&ctx, buffer, padded);

    /* NOTE: ocall_print_output uses strlen, which is unsafe for binary.
             If your OCALL expects binary, switch to an OCALL that takes an explicit length.
             For now we just send the plaintext for visibility OR base64-encode before sending. */
    ocall_print_output(outbuf);  /* safer for current OCALL; change if you want encrypted bytes sent */

    free(buffer);
    ocall_print_time("Communication 3 End");
    return pfOutput;
}