#include "Network3.h"
#include <vector>
#include <iostream>
#include <fstream>
#include <string>
#include "string.h"

#include "eapp_utils.h"
#include "edge_call.h"
#include "syscall.h"

#include <chrono>
#include <iomanip>

#include "crypto.h"
#include "aes.hpp"

#ifndef OCALL_PRINT_TIME
#define OCALL_PRINT_TIME 3
#endif

#define OCALL_PRINT_BUFFER 6
#define OCALL_PRINT_OUTPUT 10

uint8_t key[AES_KEYLEN] = {
			(uint8_t)0x1a, (uint8_t)0x2b, (uint8_t)0x3b, (uint8_t)0x4d,
			(uint8_t)0x5e, (uint8_t)0x6f, (uint8_t)0x71, (uint8_t)0x82,
			(uint8_t)0x93, (uint8_t)0x14, (uint8_t)0x25, (uint8_t)0x36,
			(uint8_t)0x47, (uint8_t)0x58, (uint8_t)0x69, (uint8_t)0x7a 
	};	

extern "C" 
{
	unsigned long ocall_print_output(char* string)
	{
		unsigned long retval;
		ocall(OCALL_PRINT_OUTPUT, string, strlen(string) + 1, &retval, sizeof(unsigned long));
		return retval;
	}

	unsigned long ocall_print_time(char* string) 
	{
		unsigned long retval;
		ocall(OCALL_PRINT_TIME, string, strlen(string) + 1, &retval, sizeof(unsigned long));
		return retval;
	}
	
	unsigned long ocall_print_buffer(char* string) 
	{
		unsigned long retval;
		ocall(OCALL_PRINT_BUFFER, string, strlen(string) + 1, &retval, sizeof(unsigned long));
		return retval;
	}

	void concatStrings(char* dest, char* concat) 
	{
    size_t destLen = strlen(dest);
    size_t concatLen = strlen(concat);

    // Ensure there is enough space in dest for concat and null terminator
    if (destLen + concatLen + 1 >= 2048) 
    {
      return;  // Not enough space, return without concatenating
    }

    // Move to the end of dest string
    dest += destLen;

    // Copy the concat string to dest
    while (*concat) 
    {
      *dest = *concat;
      dest++;
      concat++;
    }

    // Add null terminator
    *dest = '\0';
	}	
}

using namespace std;

Network::Network()
{
	ocall_print_time("Network Init 3 Start\n");

	ocall_print_buffer("Initializing Network 3...\n");

	// Fully Connected Layer
	m_Fclayer7 = new FcLayer(7, 320, 1000);  // Reduced from 1024 to 720
		
	m_vcClass.push_back("tench");
	m_vcClass.push_back("goldfish");
	m_vcClass.push_back("great");
	m_vcClass.push_back("tiger");
	m_vcClass.push_back("hammerhead");
	m_vcClass.push_back("electric");
	m_vcClass.push_back("stingray");
	m_vcClass.push_back("cock");
	m_vcClass.push_back("hen");
	m_vcClass.push_back("ostrich");
	m_vcClass.push_back("brambling");
	m_vcClass.push_back("goldfinch");
	m_vcClass.push_back("house");
	m_vcClass.push_back("junco");
	m_vcClass.push_back("indigo");
	m_vcClass.push_back("robin");
	m_vcClass.push_back("bulbul");
	m_vcClass.push_back("jay");
	m_vcClass.push_back("magpie");
	m_vcClass.push_back("chickadee");
	m_vcClass.push_back("water");
	m_vcClass.push_back("kite");
	m_vcClass.push_back("bald");
	m_vcClass.push_back("vulture");
	m_vcClass.push_back("great");
	m_vcClass.push_back("European");
	m_vcClass.push_back("common");
	m_vcClass.push_back("eft");
	m_vcClass.push_back("spotted");
	m_vcClass.push_back("axolotl");
	m_vcClass.push_back("bullfrog");
	m_vcClass.push_back("tree");
	m_vcClass.push_back("tailed");
	m_vcClass.push_back("loggerhead");
	m_vcClass.push_back("leatherback");
	m_vcClass.push_back("mud");
	m_vcClass.push_back("terrapin");
	m_vcClass.push_back("box");
	m_vcClass.push_back("banded");
	m_vcClass.push_back("common");
	m_vcClass.push_back("American");
	m_vcClass.push_back("whiptail");
	m_vcClass.push_back("agama");
	m_vcClass.push_back("frilled");
	m_vcClass.push_back("alligator");
	m_vcClass.push_back("Gila");
	m_vcClass.push_back("green");
	m_vcClass.push_back("African");
	m_vcClass.push_back("Komodo");
	m_vcClass.push_back("African");
	m_vcClass.push_back("American");
	m_vcClass.push_back("triceratops");
	m_vcClass.push_back("thunder");
	m_vcClass.push_back("ringneck");
	m_vcClass.push_back("hognose");
	m_vcClass.push_back("green");
	m_vcClass.push_back("king");
	m_vcClass.push_back("garter");
	m_vcClass.push_back("water");
	m_vcClass.push_back("vine");
	m_vcClass.push_back("night");
	m_vcClass.push_back("boa");
	m_vcClass.push_back("rock");
	m_vcClass.push_back("Indian");
	m_vcClass.push_back("green");
	m_vcClass.push_back("sea");
	m_vcClass.push_back("horned");
	m_vcClass.push_back("diamondback");
	m_vcClass.push_back("sidewinder");
	m_vcClass.push_back("trilobite");
	m_vcClass.push_back("harvestman");
	m_vcClass.push_back("scorpion");
	m_vcClass.push_back("black");
	m_vcClass.push_back("barn");
	m_vcClass.push_back("garden");
	m_vcClass.push_back("black");
	m_vcClass.push_back("tarantula");
	m_vcClass.push_back("wolf");
	m_vcClass.push_back("tick");
	m_vcClass.push_back("centipede");
	m_vcClass.push_back("black");
	m_vcClass.push_back("ptarmigan");
	m_vcClass.push_back("ruffed");
	m_vcClass.push_back("prairie");
	m_vcClass.push_back("peacock");
	m_vcClass.push_back("quail");
	m_vcClass.push_back("partridge");
	m_vcClass.push_back("African");
	m_vcClass.push_back("macaw");
	m_vcClass.push_back("sulphur");
	m_vcClass.push_back("lorikeet");
	m_vcClass.push_back("coucal");
	m_vcClass.push_back("bee");
	m_vcClass.push_back("hornbill");
	m_vcClass.push_back("hummingbird");
	m_vcClass.push_back("jacamar");
	m_vcClass.push_back("toucan");
	m_vcClass.push_back("drake");
	m_vcClass.push_back("red");
	m_vcClass.push_back("goose");
	m_vcClass.push_back("black");
	m_vcClass.push_back("tusker");
	m_vcClass.push_back("echidna");
	m_vcClass.push_back("platypus");
	m_vcClass.push_back("wallaby");
	m_vcClass.push_back("koala");
	m_vcClass.push_back("wombat");
	m_vcClass.push_back("jellyfish");
	m_vcClass.push_back("sea");
	m_vcClass.push_back("brain");
	m_vcClass.push_back("flatworm");
	m_vcClass.push_back("nematode");
	m_vcClass.push_back("conch");
	m_vcClass.push_back("snail");
	m_vcClass.push_back("slug");
	m_vcClass.push_back("sea");
	m_vcClass.push_back("chiton");
	m_vcClass.push_back("chambered");
	m_vcClass.push_back("Dungeness");
	m_vcClass.push_back("rock");
	m_vcClass.push_back("fiddler");
	m_vcClass.push_back("king");
	m_vcClass.push_back("American");
	m_vcClass.push_back("spiny");
	m_vcClass.push_back("crayfish");
	m_vcClass.push_back("hermit");
	m_vcClass.push_back("isopod");
	m_vcClass.push_back("white");
	m_vcClass.push_back("black");
	m_vcClass.push_back("spoonbill");
	m_vcClass.push_back("flamingo");
	m_vcClass.push_back("little");
	m_vcClass.push_back("American");
	m_vcClass.push_back("bittern");
	m_vcClass.push_back("crane");
	m_vcClass.push_back("limpkin");
	m_vcClass.push_back("European");
	m_vcClass.push_back("American");
	m_vcClass.push_back("bustard");
	m_vcClass.push_back("ruddy");
	m_vcClass.push_back("red");
	m_vcClass.push_back("redshank");
	m_vcClass.push_back("dowitcher");
	m_vcClass.push_back("oystercatcher");
	m_vcClass.push_back("pelican");
	m_vcClass.push_back("king");
	m_vcClass.push_back("albatross");
	m_vcClass.push_back("grey");
	m_vcClass.push_back("killer");
	m_vcClass.push_back("dugong");
	m_vcClass.push_back("sea");
	m_vcClass.push_back("Chihuahua");
	m_vcClass.push_back("Japanese");
	m_vcClass.push_back("Maltese");
	m_vcClass.push_back("Pekinese");
	m_vcClass.push_back("Shih");
	m_vcClass.push_back("Blenheim");
	m_vcClass.push_back("papillon");
	m_vcClass.push_back("toy");
	m_vcClass.push_back("Rhodesian");
	m_vcClass.push_back("Afghan");
	m_vcClass.push_back("basset");
	m_vcClass.push_back("beagle");
	m_vcClass.push_back("bloodhound");
	m_vcClass.push_back("bluetick");
	m_vcClass.push_back("black");
	m_vcClass.push_back("Walker");
	m_vcClass.push_back("English");
	m_vcClass.push_back("redbone");
	m_vcClass.push_back("borzoi");
	m_vcClass.push_back("Irish");
	m_vcClass.push_back("Italian");
	m_vcClass.push_back("whippet");
	m_vcClass.push_back("Ibizan");
	m_vcClass.push_back("Norwegian");
	m_vcClass.push_back("otterhound");
	m_vcClass.push_back("Saluki");
	m_vcClass.push_back("Scottish");
	m_vcClass.push_back("Weimaraner");
	m_vcClass.push_back("Staffordshire");
	m_vcClass.push_back("American");
	m_vcClass.push_back("Bedlington");
	m_vcClass.push_back("Border");
	m_vcClass.push_back("Kerry");
	m_vcClass.push_back("Irish");
	m_vcClass.push_back("Norfolk");
	m_vcClass.push_back("Norwich");
	m_vcClass.push_back("Yorkshire");
	m_vcClass.push_back("wire");
	m_vcClass.push_back("Lakeland");
	m_vcClass.push_back("Sealyham");
	m_vcClass.push_back("Airedale");
	m_vcClass.push_back("cairn");
	m_vcClass.push_back("Australian");
	m_vcClass.push_back("Dandie");
	m_vcClass.push_back("Boston");
	m_vcClass.push_back("miniature");
	m_vcClass.push_back("giant");
	m_vcClass.push_back("standard");
	m_vcClass.push_back("Scotch");
	m_vcClass.push_back("Tibetan");
	m_vcClass.push_back("silky");
	m_vcClass.push_back("soft");
	m_vcClass.push_back("West");
	m_vcClass.push_back("Lhasa");
	m_vcClass.push_back("flat");
	m_vcClass.push_back("curly");
	m_vcClass.push_back("golden");
	m_vcClass.push_back("Labrador");
	m_vcClass.push_back("Chesapeake");
	m_vcClass.push_back("German");
	m_vcClass.push_back("vizsla");
	m_vcClass.push_back("English");
	m_vcClass.push_back("Irish");
	m_vcClass.push_back("Gordon");
	m_vcClass.push_back("Brittany");
	m_vcClass.push_back("clumber");
	m_vcClass.push_back("English");
	m_vcClass.push_back("Welsh");
	m_vcClass.push_back("cocker");
	m_vcClass.push_back("Sussex");
	m_vcClass.push_back("Irish");
	m_vcClass.push_back("kuvasz");
	m_vcClass.push_back("schipperke");
	m_vcClass.push_back("groenendael");
	m_vcClass.push_back("malinois");
	m_vcClass.push_back("briard");
	m_vcClass.push_back("kelpie");
	m_vcClass.push_back("komondor");
	m_vcClass.push_back("Old");
	m_vcClass.push_back("Shetland");
	m_vcClass.push_back("collie");
	m_vcClass.push_back("Border");
	m_vcClass.push_back("Bouvier");
	m_vcClass.push_back("Rottweiler");
	m_vcClass.push_back("German");
	m_vcClass.push_back("Doberman");
	m_vcClass.push_back("miniature");
	m_vcClass.push_back("Greater");
	m_vcClass.push_back("Bernese");
	m_vcClass.push_back("Appenzeller");
	m_vcClass.push_back("EntleBucher");
	m_vcClass.push_back("boxer");
	m_vcClass.push_back("bull");
	m_vcClass.push_back("Tibetan");
	m_vcClass.push_back("French");
	m_vcClass.push_back("Great");
	m_vcClass.push_back("Saint");
	m_vcClass.push_back("Eskimo");
	m_vcClass.push_back("malamute");
	m_vcClass.push_back("Siberian");
	m_vcClass.push_back("dalmatian");
	m_vcClass.push_back("affenpinscher");
	m_vcClass.push_back("basenji");
	m_vcClass.push_back("pug");
	m_vcClass.push_back("Leonberg");
	m_vcClass.push_back("Newfoundland");
	m_vcClass.push_back("Great");
	m_vcClass.push_back("Samoyed");
	m_vcClass.push_back("Pomeranian");
	m_vcClass.push_back("chow");
	m_vcClass.push_back("keeshond");
	m_vcClass.push_back("Brabancon");
	m_vcClass.push_back("Pembroke");
	m_vcClass.push_back("Cardigan");
	m_vcClass.push_back("toy");
	m_vcClass.push_back("miniature");
	m_vcClass.push_back("standard");
	m_vcClass.push_back("Mexican");
	m_vcClass.push_back("timber");
	m_vcClass.push_back("white");
	m_vcClass.push_back("red");
	m_vcClass.push_back("coyote");
	m_vcClass.push_back("dingo");
	m_vcClass.push_back("dhole");
	m_vcClass.push_back("African");
	m_vcClass.push_back("hyena");
	m_vcClass.push_back("red");
	m_vcClass.push_back("kit");
	m_vcClass.push_back("Arctic");
	m_vcClass.push_back("grey");
	m_vcClass.push_back("tabby");
	m_vcClass.push_back("tiger");
	m_vcClass.push_back("Persian");
	m_vcClass.push_back("Siamese");
	m_vcClass.push_back("Egyptian");
	m_vcClass.push_back("cougar");
	m_vcClass.push_back("lynx");
	m_vcClass.push_back("leopard");
	m_vcClass.push_back("snow");
	m_vcClass.push_back("jaguar");
	m_vcClass.push_back("lion");
	m_vcClass.push_back("tiger");
	m_vcClass.push_back("cheetah");
	m_vcClass.push_back("brown");
	m_vcClass.push_back("American");
	m_vcClass.push_back("ice");
	m_vcClass.push_back("sloth");
	m_vcClass.push_back("mongoose");
	m_vcClass.push_back("meerkat");
	m_vcClass.push_back("tiger");
	m_vcClass.push_back("ladybug");
	m_vcClass.push_back("ground");
	m_vcClass.push_back("long");
	m_vcClass.push_back("leaf");
	m_vcClass.push_back("dung");
	m_vcClass.push_back("rhinoceros");
	m_vcClass.push_back("weevil");
	m_vcClass.push_back("fly");
	m_vcClass.push_back("bee");
	m_vcClass.push_back("ant");
	m_vcClass.push_back("grasshopper");
	m_vcClass.push_back("cricket");
	m_vcClass.push_back("walking");
	m_vcClass.push_back("cockroach");
	m_vcClass.push_back("mantis");
	m_vcClass.push_back("cicada");
	m_vcClass.push_back("leafhopper");
	m_vcClass.push_back("lacewing");
	m_vcClass.push_back("dragonfly");
	m_vcClass.push_back("damselfly");
	m_vcClass.push_back("admiral");
	m_vcClass.push_back("ringlet");
	m_vcClass.push_back("monarch");
	m_vcClass.push_back("cabbage");
	m_vcClass.push_back("sulphur");
	m_vcClass.push_back("lycaenid");
	m_vcClass.push_back("starfish");
	m_vcClass.push_back("sea");
	m_vcClass.push_back("sea");
	m_vcClass.push_back("wood");
	m_vcClass.push_back("hare");
	m_vcClass.push_back("Angora");
	m_vcClass.push_back("hamster");
	m_vcClass.push_back("porcupine");
	m_vcClass.push_back("fox");
	m_vcClass.push_back("marmot");
	m_vcClass.push_back("beaver");
	m_vcClass.push_back("guinea");
	m_vcClass.push_back("sorrel");
	m_vcClass.push_back("zebra");
	m_vcClass.push_back("hog");
	m_vcClass.push_back("wild");
	m_vcClass.push_back("warthog");
	m_vcClass.push_back("hippopotamus");
	m_vcClass.push_back("ox");
	m_vcClass.push_back("water");
	m_vcClass.push_back("bison");
	m_vcClass.push_back("ram");
	m_vcClass.push_back("bighorn");
	m_vcClass.push_back("ibex");
	m_vcClass.push_back("hartebeest");
	m_vcClass.push_back("impala");
	m_vcClass.push_back("gazelle");
	m_vcClass.push_back("Arabian");
	m_vcClass.push_back("llama");
	m_vcClass.push_back("weasel");
	m_vcClass.push_back("mink");
	m_vcClass.push_back("polecat");
	m_vcClass.push_back("black");
	m_vcClass.push_back("otter");
	m_vcClass.push_back("skunk");
	m_vcClass.push_back("badger");
	m_vcClass.push_back("armadillo");
	m_vcClass.push_back("three");
	m_vcClass.push_back("orangutan");
	m_vcClass.push_back("gorilla");
	m_vcClass.push_back("chimpanzee");
	m_vcClass.push_back("gibbon");
	m_vcClass.push_back("siamang");
	m_vcClass.push_back("guenon");
	m_vcClass.push_back("patas");
	m_vcClass.push_back("baboon");
	m_vcClass.push_back("macaque");
	m_vcClass.push_back("langur");
	m_vcClass.push_back("colobus");
	m_vcClass.push_back("proboscis");
	m_vcClass.push_back("marmoset");
	m_vcClass.push_back("capuchin");
	m_vcClass.push_back("howler");
	m_vcClass.push_back("titi");
	m_vcClass.push_back("spider");
	m_vcClass.push_back("squirrel");
	m_vcClass.push_back("Madagascar");
	m_vcClass.push_back("indri");
	m_vcClass.push_back("Indian");
	m_vcClass.push_back("African");
	m_vcClass.push_back("lesser");
	m_vcClass.push_back("giant");
	m_vcClass.push_back("barracouta");
	m_vcClass.push_back("eel");
	m_vcClass.push_back("coho");
	m_vcClass.push_back("rock");
	m_vcClass.push_back("anemone");
	m_vcClass.push_back("sturgeon");
	m_vcClass.push_back("gar");
	m_vcClass.push_back("lionfish");
	m_vcClass.push_back("puffer");
	m_vcClass.push_back("abacus");
	m_vcClass.push_back("abaya");
	m_vcClass.push_back("academic");
	m_vcClass.push_back("accordion");
	m_vcClass.push_back("acoustic");
	m_vcClass.push_back("aircraft");
	m_vcClass.push_back("airliner");
	m_vcClass.push_back("airship");
	m_vcClass.push_back("altar");
	m_vcClass.push_back("ambulance");
	m_vcClass.push_back("amphibian");
	m_vcClass.push_back("analog");
	m_vcClass.push_back("apiary");
	m_vcClass.push_back("apron");
	m_vcClass.push_back("ashcan");
	m_vcClass.push_back("assault");
	m_vcClass.push_back("backpack");
	m_vcClass.push_back("bakery");
	m_vcClass.push_back("balance");
	m_vcClass.push_back("balloon");
	m_vcClass.push_back("ballpoint");
	m_vcClass.push_back("Band");
	m_vcClass.push_back("banjo");
	m_vcClass.push_back("bannister");
	m_vcClass.push_back("barbell");
	m_vcClass.push_back("barber");
	m_vcClass.push_back("barbershop");
	m_vcClass.push_back("barn");
	m_vcClass.push_back("barometer");
	m_vcClass.push_back("barrel");
	m_vcClass.push_back("barrow");
	m_vcClass.push_back("baseball");
	m_vcClass.push_back("basketball");
	m_vcClass.push_back("bassinet");
	m_vcClass.push_back("bassoon");
	m_vcClass.push_back("bathing");
	m_vcClass.push_back("bath");
	m_vcClass.push_back("bathtub");
	m_vcClass.push_back("beach");
	m_vcClass.push_back("beacon");
	m_vcClass.push_back("beaker");
	m_vcClass.push_back("bearskin");
	m_vcClass.push_back("beer");
	m_vcClass.push_back("beer");
	m_vcClass.push_back("bell");
	m_vcClass.push_back("bib");
	m_vcClass.push_back("bicycle");
	m_vcClass.push_back("bikini");
	m_vcClass.push_back("binder");
	m_vcClass.push_back("binoculars");
	m_vcClass.push_back("birdhouse");
	m_vcClass.push_back("boathouse");
	m_vcClass.push_back("bobsled");
	m_vcClass.push_back("bolo");
	m_vcClass.push_back("bonnet");
	m_vcClass.push_back("bookcase");
	m_vcClass.push_back("bookshop");
	m_vcClass.push_back("bottlecap");
	m_vcClass.push_back("bow");
	m_vcClass.push_back("bow");
	m_vcClass.push_back("brass");
	m_vcClass.push_back("brassiere");
	m_vcClass.push_back("breakwater");
	m_vcClass.push_back("breastplate");
	m_vcClass.push_back("broom");
	m_vcClass.push_back("bucket");
	m_vcClass.push_back("buckle");
	m_vcClass.push_back("bulletproof");
	m_vcClass.push_back("bullet");
	m_vcClass.push_back("butcher");
	m_vcClass.push_back("cab");
	m_vcClass.push_back("caldron");
	m_vcClass.push_back("candle");
	m_vcClass.push_back("cannon");
	m_vcClass.push_back("canoe");
	m_vcClass.push_back("can");
	m_vcClass.push_back("cardigan");
	m_vcClass.push_back("car");
	m_vcClass.push_back("carousel");
	m_vcClass.push_back("carpenter's");
	m_vcClass.push_back("carton");
	m_vcClass.push_back("car");
	m_vcClass.push_back("cash");
	m_vcClass.push_back("cassette");
	m_vcClass.push_back("cassette");
	m_vcClass.push_back("castle");
	m_vcClass.push_back("catamaran");
	m_vcClass.push_back("CD");
	m_vcClass.push_back("cello");
	m_vcClass.push_back("cellular");
	m_vcClass.push_back("chain");
	m_vcClass.push_back("chainlink");
	m_vcClass.push_back("chain");
	m_vcClass.push_back("chain");
	m_vcClass.push_back("chest");
	m_vcClass.push_back("chiffonier");
	m_vcClass.push_back("chime");
	m_vcClass.push_back("china");
	m_vcClass.push_back("Christmas");
	m_vcClass.push_back("church");
	m_vcClass.push_back("cinema");
	m_vcClass.push_back("cleaver");
	m_vcClass.push_back("cliff");
	m_vcClass.push_back("cloak");
	m_vcClass.push_back("clog");
	m_vcClass.push_back("cocktail");
	m_vcClass.push_back("coffee");
	m_vcClass.push_back("coffeepot");
	m_vcClass.push_back("coil");
	m_vcClass.push_back("combination");
	m_vcClass.push_back("computer");
	m_vcClass.push_back("confectionery");
	m_vcClass.push_back("container");
	m_vcClass.push_back("convertible");
	m_vcClass.push_back("corkscrew");
	m_vcClass.push_back("cornet");
	m_vcClass.push_back("cowboy");
	m_vcClass.push_back("cowboy");
	m_vcClass.push_back("cradle");
	m_vcClass.push_back("crane");
	m_vcClass.push_back("crash");
	m_vcClass.push_back("crate");
	m_vcClass.push_back("crib");
	m_vcClass.push_back("Crock");
	m_vcClass.push_back("croquet");
	m_vcClass.push_back("crutch");
	m_vcClass.push_back("cuirass");
	m_vcClass.push_back("dam");
	m_vcClass.push_back("desk");
	m_vcClass.push_back("desktop");
	m_vcClass.push_back("dial");
	m_vcClass.push_back("diaper");
	m_vcClass.push_back("digital");
	m_vcClass.push_back("digital");
	m_vcClass.push_back("dining");
	m_vcClass.push_back("dishrag");
	m_vcClass.push_back("dishwasher");
	m_vcClass.push_back("disk");
	m_vcClass.push_back("dock");
	m_vcClass.push_back("dogsled");
	m_vcClass.push_back("dome");
	m_vcClass.push_back("doormat");
	m_vcClass.push_back("drilling");
	m_vcClass.push_back("drum");
	m_vcClass.push_back("drumstick");
	m_vcClass.push_back("dumbbell");
	m_vcClass.push_back("Dutch");
	m_vcClass.push_back("electric");
	m_vcClass.push_back("electric");
	m_vcClass.push_back("electric");
	m_vcClass.push_back("entertainment");
	m_vcClass.push_back("envelope");
	m_vcClass.push_back("espresso");
	m_vcClass.push_back("face");
	m_vcClass.push_back("feather");
	m_vcClass.push_back("file");
	m_vcClass.push_back("fireboat");
	m_vcClass.push_back("fire");
	m_vcClass.push_back("fire");
	m_vcClass.push_back("flagpole");
	m_vcClass.push_back("flute");
	m_vcClass.push_back("folding");
	m_vcClass.push_back("football");
	m_vcClass.push_back("forklift");
	m_vcClass.push_back("fountain");
	m_vcClass.push_back("fountain");
	m_vcClass.push_back("four");
	m_vcClass.push_back("freight");
	m_vcClass.push_back("French");
	m_vcClass.push_back("frying");
	m_vcClass.push_back("fur");
	m_vcClass.push_back("garbage");
	m_vcClass.push_back("gasmask");
	m_vcClass.push_back("gas");
	m_vcClass.push_back("goblet");
	m_vcClass.push_back("go");
	m_vcClass.push_back("golf");
	m_vcClass.push_back("golfcart");
	m_vcClass.push_back("gondola");
	m_vcClass.push_back("gong");
	m_vcClass.push_back("gown");
	m_vcClass.push_back("grand");
	m_vcClass.push_back("greenhouse");
	m_vcClass.push_back("grille");
	m_vcClass.push_back("grocery");
	m_vcClass.push_back("guillotine");
	m_vcClass.push_back("hair");
	m_vcClass.push_back("hair");
	m_vcClass.push_back("half");
	m_vcClass.push_back("hammer");
	m_vcClass.push_back("hamper");
	m_vcClass.push_back("hand");
	m_vcClass.push_back("hand");
	m_vcClass.push_back("handkerchief");
	m_vcClass.push_back("hard");
	m_vcClass.push_back("harmonica");
	m_vcClass.push_back("harp");
	m_vcClass.push_back("harvester");
	m_vcClass.push_back("hatchet");
	m_vcClass.push_back("holster");
	m_vcClass.push_back("home");
	m_vcClass.push_back("honeycomb");
	m_vcClass.push_back("hook");
	m_vcClass.push_back("hoopskirt");
	m_vcClass.push_back("horizontal");
	m_vcClass.push_back("horse");
	m_vcClass.push_back("hourglass");
	m_vcClass.push_back("iPod");
	m_vcClass.push_back("iron");
	m_vcClass.push_back("jack");
	m_vcClass.push_back("jean");
	m_vcClass.push_back("jeep");
	m_vcClass.push_back("jersey");
	m_vcClass.push_back("jigsaw");
	m_vcClass.push_back("jinrikisha");
	m_vcClass.push_back("joystick");
	m_vcClass.push_back("kimono");
	m_vcClass.push_back("knee");
	m_vcClass.push_back("knot");
	m_vcClass.push_back("lab");
	m_vcClass.push_back("ladle");
	m_vcClass.push_back("lampshade");
	m_vcClass.push_back("laptop");
	m_vcClass.push_back("lawn");
	m_vcClass.push_back("lens");
	m_vcClass.push_back("letter");
	m_vcClass.push_back("library");
	m_vcClass.push_back("lifeboat");
	m_vcClass.push_back("lighter");
	m_vcClass.push_back("limousine");
	m_vcClass.push_back("liner");
	m_vcClass.push_back("lipstick");
	m_vcClass.push_back("Loafer");
	m_vcClass.push_back("lotion");
	m_vcClass.push_back("loudspeaker");
	m_vcClass.push_back("loupe");
	m_vcClass.push_back("lumbermill");
	m_vcClass.push_back("magnetic");
	m_vcClass.push_back("mailbag");
	m_vcClass.push_back("mailbox");
	m_vcClass.push_back("maillot");
	m_vcClass.push_back("manhole");
	m_vcClass.push_back("maraca");
	m_vcClass.push_back("marimba");
	m_vcClass.push_back("mask");
	m_vcClass.push_back("matchstick");
	m_vcClass.push_back("maypole");
	m_vcClass.push_back("maze");
	m_vcClass.push_back("measuring");
	m_vcClass.push_back("medicine");
	m_vcClass.push_back("megalith");
	m_vcClass.push_back("microphone");
	m_vcClass.push_back("microwave");
	m_vcClass.push_back("military");
	m_vcClass.push_back("milk");
	m_vcClass.push_back("minibus");
	m_vcClass.push_back("miniskirt");
	m_vcClass.push_back("minivan");
	m_vcClass.push_back("missile");
	m_vcClass.push_back("mitten");
	m_vcClass.push_back("mixing");
	m_vcClass.push_back("mobile");
	m_vcClass.push_back("Model");
	m_vcClass.push_back("modem");
	m_vcClass.push_back("monastery");
	m_vcClass.push_back("monitor");
	m_vcClass.push_back("moped");
	m_vcClass.push_back("mortar");
	m_vcClass.push_back("mortarboard");
	m_vcClass.push_back("mosque");
	m_vcClass.push_back("mosquito");
	m_vcClass.push_back("motor");
	m_vcClass.push_back("mountain");
	m_vcClass.push_back("mountain");
	m_vcClass.push_back("mouse");
	m_vcClass.push_back("mousetrap");
	m_vcClass.push_back("moving");
	m_vcClass.push_back("muzzle");
	m_vcClass.push_back("nail");
	m_vcClass.push_back("neck");
	m_vcClass.push_back("necklace");
	m_vcClass.push_back("nipple");
	m_vcClass.push_back("notebook");
	m_vcClass.push_back("obelisk");
	m_vcClass.push_back("oboe");
	m_vcClass.push_back("ocarina");
	m_vcClass.push_back("odometer");
	m_vcClass.push_back("oil");
	m_vcClass.push_back("organ");
	m_vcClass.push_back("oscilloscope");
	m_vcClass.push_back("overskirt");
	m_vcClass.push_back("oxcart");
	m_vcClass.push_back("oxygen");
	m_vcClass.push_back("packet");
	m_vcClass.push_back("paddle");
	m_vcClass.push_back("paddlewheel");
	m_vcClass.push_back("padlock");
	m_vcClass.push_back("paintbrush");
	m_vcClass.push_back("pajama");
	m_vcClass.push_back("palace");
	m_vcClass.push_back("panpipe");
	m_vcClass.push_back("paper");
	m_vcClass.push_back("parachute");
	m_vcClass.push_back("parallel");
	m_vcClass.push_back("park");
	m_vcClass.push_back("parking");
	m_vcClass.push_back("passenger");
	m_vcClass.push_back("patio");
	m_vcClass.push_back("pay");
	m_vcClass.push_back("pedestal");
	m_vcClass.push_back("pencil");
	m_vcClass.push_back("pencil");
	m_vcClass.push_back("perfume");
	m_vcClass.push_back("Petri");
	m_vcClass.push_back("photocopier");
	m_vcClass.push_back("pick");
	m_vcClass.push_back("pickelhaube");
	m_vcClass.push_back("picket");
	m_vcClass.push_back("pickup");
	m_vcClass.push_back("pier");
	m_vcClass.push_back("piggy");
	m_vcClass.push_back("pill");
	m_vcClass.push_back("pillow");
	m_vcClass.push_back("ping");
	m_vcClass.push_back("pinwheel");
	m_vcClass.push_back("pirate");
	m_vcClass.push_back("pitcher");
	m_vcClass.push_back("plane");
	m_vcClass.push_back("planetarium");
	m_vcClass.push_back("plastic");
	m_vcClass.push_back("plate");
	m_vcClass.push_back("plow");
	m_vcClass.push_back("plunger");
	m_vcClass.push_back("Polaroid");
	m_vcClass.push_back("pole");
	m_vcClass.push_back("police");
	m_vcClass.push_back("poncho");
	m_vcClass.push_back("pool");
	m_vcClass.push_back("pop");
	m_vcClass.push_back("pot");
	m_vcClass.push_back("potter's");
	m_vcClass.push_back("power");
	m_vcClass.push_back("prayer");
	m_vcClass.push_back("printer");
	m_vcClass.push_back("prison");
	m_vcClass.push_back("projectile");
	m_vcClass.push_back("projector");
	m_vcClass.push_back("puck");
	m_vcClass.push_back("punching");
	m_vcClass.push_back("purse");
	m_vcClass.push_back("quill");
	m_vcClass.push_back("quilt");
	m_vcClass.push_back("racer");
	m_vcClass.push_back("racket");
	m_vcClass.push_back("radiator");
	m_vcClass.push_back("radio");
	m_vcClass.push_back("radio");
	m_vcClass.push_back("rain");
	m_vcClass.push_back("recreational");
	m_vcClass.push_back("reel");
	m_vcClass.push_back("reflex");
	m_vcClass.push_back("refrigerator");
	m_vcClass.push_back("remote");
	m_vcClass.push_back("restaurant");
	m_vcClass.push_back("revolver");
	m_vcClass.push_back("rifle");
	m_vcClass.push_back("rocking");
	m_vcClass.push_back("rotisserie");
	m_vcClass.push_back("rubber");
	m_vcClass.push_back("rugby");
	m_vcClass.push_back("rule");
	m_vcClass.push_back("running");
	m_vcClass.push_back("safe");
	m_vcClass.push_back("safety");
	m_vcClass.push_back("sandal");
	m_vcClass.push_back("sarong");
	m_vcClass.push_back("sax");
	m_vcClass.push_back("scabbard");
	m_vcClass.push_back("scale");
	m_vcClass.push_back("school");
	m_vcClass.push_back("schooner");
	m_vcClass.push_back("scoreboard");
	m_vcClass.push_back("screen");
	m_vcClass.push_back("screw");
	m_vcClass.push_back("screwdriver");
	m_vcClass.push_back("seat");
	m_vcClass.push_back("sewing");
	m_vcClass.push_back("shield");
	m_vcClass.push_back("shoe");
	m_vcClass.push_back("shoji");
	m_vcClass.push_back("shopping");
	m_vcClass.push_back("shopping");
	m_vcClass.push_back("shovel");
	m_vcClass.push_back("shower");
	m_vcClass.push_back("shower");
	m_vcClass.push_back("ski");
	m_vcClass.push_back("ski");
	m_vcClass.push_back("sleeping");
	m_vcClass.push_back("slide");
	m_vcClass.push_back("sliding");
	m_vcClass.push_back("slot");
	m_vcClass.push_back("snorkel");
	m_vcClass.push_back("snowmobile");
	m_vcClass.push_back("snowplow");
	m_vcClass.push_back("soap");
	m_vcClass.push_back("soccer");
	m_vcClass.push_back("sock");
	m_vcClass.push_back("solar");
	m_vcClass.push_back("sombrero");
	m_vcClass.push_back("soup");
	m_vcClass.push_back("space");
	m_vcClass.push_back("space");
	m_vcClass.push_back("space");
	m_vcClass.push_back("spatula");
	m_vcClass.push_back("speedboat");
	m_vcClass.push_back("spider");
	m_vcClass.push_back("spindle");
	m_vcClass.push_back("sports");
	m_vcClass.push_back("spotlight");
	m_vcClass.push_back("stage");
	m_vcClass.push_back("steam");
	m_vcClass.push_back("steel");
	m_vcClass.push_back("steel");
	m_vcClass.push_back("stethoscope");
	m_vcClass.push_back("stole");
	m_vcClass.push_back("stone");
	m_vcClass.push_back("stopwatch");
	m_vcClass.push_back("stove");
	m_vcClass.push_back("strainer");
	m_vcClass.push_back("streetcar");
	m_vcClass.push_back("stretcher");
	m_vcClass.push_back("studio");
	m_vcClass.push_back("stupa");
	m_vcClass.push_back("submarine");
	m_vcClass.push_back("suit");
	m_vcClass.push_back("sundial");
	m_vcClass.push_back("sunglass");
	m_vcClass.push_back("sunglasses");
	m_vcClass.push_back("sunscreen");
	m_vcClass.push_back("suspension");
	m_vcClass.push_back("swab");
	m_vcClass.push_back("sweatshirt");
	m_vcClass.push_back("swimming");
	m_vcClass.push_back("swing");
	m_vcClass.push_back("switch");
	m_vcClass.push_back("syringe");
	m_vcClass.push_back("table");
	m_vcClass.push_back("tank");
	m_vcClass.push_back("tape");
	m_vcClass.push_back("teapot");
	m_vcClass.push_back("teddy");
	m_vcClass.push_back("television");
	m_vcClass.push_back("tennis");
	m_vcClass.push_back("thatch");
	m_vcClass.push_back("theater");
	m_vcClass.push_back("thimble");
	m_vcClass.push_back("thresher");
	m_vcClass.push_back("throne");
	m_vcClass.push_back("tile");
	m_vcClass.push_back("toaster");
	m_vcClass.push_back("tobacco");
	m_vcClass.push_back("toilet");
	m_vcClass.push_back("torch");
	m_vcClass.push_back("totem");
	m_vcClass.push_back("tow");
	m_vcClass.push_back("toyshop");
	m_vcClass.push_back("tractor");
	m_vcClass.push_back("trailer");
	m_vcClass.push_back("tray");
	m_vcClass.push_back("trench");
	m_vcClass.push_back("tricycle");
	m_vcClass.push_back("trimaran");
	m_vcClass.push_back("tripod");
	m_vcClass.push_back("triumphal");
	m_vcClass.push_back("trolleybus");
	m_vcClass.push_back("trombone");
	m_vcClass.push_back("tub");
	m_vcClass.push_back("turnstile");
	m_vcClass.push_back("typewriter");
	m_vcClass.push_back("umbrella");
	m_vcClass.push_back("unicycle");
	m_vcClass.push_back("upright");
	m_vcClass.push_back("vacuum");
	m_vcClass.push_back("vase");
	m_vcClass.push_back("vault");
	m_vcClass.push_back("velvet");
	m_vcClass.push_back("vending");
	m_vcClass.push_back("vestment");
	m_vcClass.push_back("viaduct");
	m_vcClass.push_back("violin");
	m_vcClass.push_back("volleyball");
	m_vcClass.push_back("waffle");
	m_vcClass.push_back("wall");
	m_vcClass.push_back("wallet");
	m_vcClass.push_back("wardrobe");
	m_vcClass.push_back("warplane");
	m_vcClass.push_back("washbasin");
	m_vcClass.push_back("washer");
	m_vcClass.push_back("water");
	m_vcClass.push_back("water");
	m_vcClass.push_back("water");
	m_vcClass.push_back("whiskey");
	m_vcClass.push_back("whistle");
	m_vcClass.push_back("wig");
	m_vcClass.push_back("window");
	m_vcClass.push_back("window");
	m_vcClass.push_back("Windsor");
	m_vcClass.push_back("wine");
	m_vcClass.push_back("wing");
	m_vcClass.push_back("wok");
	m_vcClass.push_back("wooden");
	m_vcClass.push_back("wool");
	m_vcClass.push_back("worm");
	m_vcClass.push_back("wreck");
	m_vcClass.push_back("yawl");
	m_vcClass.push_back("yurt");
	m_vcClass.push_back("web");
	m_vcClass.push_back("comic");
	m_vcClass.push_back("crossword");
	m_vcClass.push_back("street");
	m_vcClass.push_back("traffic");
	m_vcClass.push_back("book");
	m_vcClass.push_back("menu");
	m_vcClass.push_back("plate");
	m_vcClass.push_back("guacamole");
	m_vcClass.push_back("consomme");
	m_vcClass.push_back("hot");
	m_vcClass.push_back("trifle");
	m_vcClass.push_back("ice");
	m_vcClass.push_back("ice");
	m_vcClass.push_back("French");
	m_vcClass.push_back("bagel");
	m_vcClass.push_back("pretzel");
	m_vcClass.push_back("cheeseburger");
	m_vcClass.push_back("hotdog");
	m_vcClass.push_back("mashed");
	m_vcClass.push_back("head");
	m_vcClass.push_back("broccoli");
	m_vcClass.push_back("cauliflower");
	m_vcClass.push_back("zucchini");
	m_vcClass.push_back("spaghetti");
	m_vcClass.push_back("acorn");
	m_vcClass.push_back("butternut");
	m_vcClass.push_back("cucumber");
	m_vcClass.push_back("artichoke");
	m_vcClass.push_back("bell");
	m_vcClass.push_back("cardoon");
	m_vcClass.push_back("mushroom");
	m_vcClass.push_back("Granny");
	m_vcClass.push_back("strawberry");
	m_vcClass.push_back("orange");
	m_vcClass.push_back("lemon");
	m_vcClass.push_back("fig");
	m_vcClass.push_back("pineapple");
	m_vcClass.push_back("banana");
	m_vcClass.push_back("jackfruit");
	m_vcClass.push_back("custard");
	m_vcClass.push_back("pomegranate");
	m_vcClass.push_back("hay");
	m_vcClass.push_back("carbonara");
	m_vcClass.push_back("chocolate");
	m_vcClass.push_back("dough");
	m_vcClass.push_back("meat");
	m_vcClass.push_back("pizza");
	m_vcClass.push_back("potpie");
	m_vcClass.push_back("burrito");
	m_vcClass.push_back("red");
	m_vcClass.push_back("espresso");
	m_vcClass.push_back("cup");
	m_vcClass.push_back("eggnog");
	m_vcClass.push_back("alp");
	m_vcClass.push_back("bubble");
	m_vcClass.push_back("cliff");
	m_vcClass.push_back("coral");
	m_vcClass.push_back("geyser");
	m_vcClass.push_back("lakeside");
	m_vcClass.push_back("promontory");
	m_vcClass.push_back("sandbar");
	m_vcClass.push_back("seashore");
	m_vcClass.push_back("valley");
	m_vcClass.push_back("volcano");
	m_vcClass.push_back("ballplayer");
	m_vcClass.push_back("groom");
	m_vcClass.push_back("scuba");
	m_vcClass.push_back("rapeseed");
	m_vcClass.push_back("daisy");
	m_vcClass.push_back("yellow");
	m_vcClass.push_back("corn");
	m_vcClass.push_back("acorn");
	m_vcClass.push_back("hip");
	m_vcClass.push_back("buckeye");
	m_vcClass.push_back("coral");
	m_vcClass.push_back("agaric");
	m_vcClass.push_back("gyromitra");
	m_vcClass.push_back("stinkhorn");
	m_vcClass.push_back("earthstar");
	m_vcClass.push_back("hen");
	m_vcClass.push_back("bolete");
	m_vcClass.push_back("ear");
	m_vcClass.push_back("toilet");
	m_vcClass.push_back("net");
	m_vcClass.push_back("scooter");
	
	ocall_print_buffer("Initializing Network 3 Done...\n");
	
	ocall_print_time("Network Init 3 End");
}


Network::~Network()
{
    delete m_Fclayer7;
}


float* Network::Forward(float* input)
{
	ocall_print_time("Inference 3 Start");
	
	ocall_print_buffer("Getting output...\n");
	
  	m_Fclayer7->forward(input);

  	float *pfOutput = m_Fclayer7->GetOutput();
	vector <int> argmax;
	vector <float> Max;

  	int nOutputSize = m_Fclayer7->GetOutputSize();
	for (int i = 0; i<nOutputSize; i++)
	{
		if (pfOutput[i] > 0.5)
		{
			argmax.push_back(i);
			Max.push_back(pfOutput[i]);
		}
	}
	ocall_print_time("Inference 3 End");
	
	ocall_print_time("Communication 3 Start");
	
	struct AES_ctx ctx;
	AES_init_ctx_iv(&ctx, key, iv);
	
	char outputBuf[396] = { 0 };
	
	for (int i = 0; i < argmax.size(); i++)
	{
		char print[32];
		snprintf(print, sizeof(print), "%10f: %d: %s\n", Max[i], argmax[i], m_vcClass[argmax[i]]);
		concatStrings(outputBuf, print);
	}
	//apply padding
	size_t length = sizeof(outputBuf);
	uint8_t* buffer = (uint8_t*)malloc(length + (AES_BLOCKLEN - (length % AES_BLOCKLEN)));
	memcpy(buffer, outputBuf, length);
	size_t padded_length = length;
	pad_buffer(buffer, &padded_length);
	
	//encrypt
	AES_CBC_encrypt_buffer(&ctx, buffer, padded_length);
	ocall_print_output((char*)buffer);

	ocall_print_time("Communication 3 End");
    
  return pfOutput;
}
